package ${packageName}

// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
// ATTENTION:
// This controller was generated by (FN)UI and should not be modified because any
// modification to this file will be lost when (FN)UI is executed again.
// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

import fnui.core.annotations.GeneratedCode

<%# extend('ControllerImports', node) %>

<%# extend('ControllerAnnotations', node) %>
@GeneratedCode
class ${name} {
    static namespace = 'generated'
    <% if (node['defaultAction']) { %>
    static defaultAction = '${node['defaultAction']}'
    <% } %>\

    <%# extend('ControllerBody', node) %>

    <% node.findAllByType('serviceDeclaration').each { serviceNode -> %>
    ${ serviceNode['type'].classDeclaration} ${ serviceNode.data['varName']}
    <% } %>
    <% node.findByType('actions')?.children.each { action -> %>
    <%# translate('Action', action) %>
    <% } %>
}